image: alpine:latest


variables:
  # deploy script
  GIT_REPO_URL: git@gitlab.com:what-digital/deploy-django.git
  # These infos are set in https://gitlab.com/what-digital/deploy-django/tree/master/group_vars
  SERVER_SSH_KEY_FILENAME: server-project_name.pem
  SECRETS_YML_FILENAME: secrets-project_name.yml
  ANSIBLE_PROJECT_NAME_PROD: project_name-prod
  ANSIBLE_PROJECT_NAME_STAGE: project_name-stage
  URL_PROD: https://project_name.tld
  URL_STAGE: https://project_name-stage.what.digital


before_script:
  # install required packages
  - apk update && apk add bash openssh-client python git python python-dev ansible python-dev py-pip
  - bash
  - pip install --upgrade pip
  - pip install boto httplib2

  # trust gitlab.com
  - mkdir ~/.ssh/
  - touch ~/.ssh/known_hosts
  - ssh-keyscan gitlab.com >> /root/.ssh/known_hosts

  # dump ssh key
  - echo "$ANSIBLE_PROJECT_DEPLOY_KEY" > ansible-project-deploy-key.pem
  - chmod 600 ansible-project-deploy-key.pem

  # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)

  # clone the ansible script
  # http://superuser.com/questions/232373/how-to-tell-git-which-private-key-to-use
  - ssh-agent sh -c "ssh-add ansible-project-deploy-key.pem; git clone $GIT_REPO_URL deploy-script"

  # get deploy script
  - cd deploy-script
  - git submodule update --recursive

  # copy credentials to their place
  - mkdir credentials
  - echo "$SERVER_SSH_KEY_STAGE" > credentials/server-project_name-stage.pem
  - echo "$SERVER_SSH_KEY_PROD" > credentials/server-project_name-prod.pem
  - echo "$SECRETS_YML_STAGE" > credentials/secrets-project_name-stage.yml
  - echo "$SECRETS_YML_PROD" > credentials/secrets-project_name-prod.yml
  - chmod 600 -R credentials/*


stages:
  - deploy


deploy to production:
  stage: deploy
  script:
    - ./deploy $ANSIBLE_PROJECT_NAME_PROD 3-deploy-site.yml
  environment:
    name: production
    url: $URL_PROD
  only:
    refs:
      - master
  except: 
    changes:
      - docs/*
      - docs/**/*
      - README.md


deploy to stage:
  stage: deploy
  script:
    - ./deploy $ANSIBLE_PROJECT_NAME_STAGE 3-deploy-site.yml
  environment:
    name: stage
    url: $URL_STAGE
  only:
    refs:
      - stage
  except: 
    changes:
      - docs/*
      - docs/**/*
      - README.md
