version: '2'

# Live Mode
# firstly remove /static_collected from .dockerignore
# then follow the guide - https://docs.divio.com/en/latest/how-to/local-in-live-configuration/
services:
    web:
        build:
            context: '.'
            dockerfile: Dockerfile
        links:
            - 'db:postgres'
        ports:
            - '8000:80'
        volumes:
            - '.:/app:rw'
            - './data:/data:rw'
        command: python manage.py runserver 0.0.0.0:80
        env_file: backend/.env

    frontend:
        build:
            context: '.'
            dockerfile: frontend.Dockerfile
        ports:
            - '8090:8090'
        volumes:
            - '.:/app:rw'
            - node_modules:/app/frontend/node_modules
        command: yarn webpack-dev-server-in-docker

    db:
        image: postgres:9.6-alpine
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: 'db'
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - '.:/app:rw'

volumes:
    node_modules:
