version: "2"

services:
  web:
    build: "."
    links:
      - "db:postgres"
    ports:
      - "8000:80"
    volumes:
      - ".:/app:rw"
      - "./data:/data:rw"
    # live mode https://docs.divio.com/en/latest/how-to/local-in-live-mode.html.
    command: python manage.py runserver 0.0.0.0:80
    env_file: .env-for-docker

  db:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ".:/app:rw"
